const QUESTIONS_DB = {
  react: [
    { id: 1, q: "What is JSX in React?", options: ["A JavaScript XML syntax extension", "A Java framework", "A CSS preprocessor", "A database query language"], ans: 0, diff: "Easy" },
    { id: 2, q: "Which hook is used to manage state in functional components?", options: ["useEffect", "useState", "useContext", "useRef"], ans: 1, diff: "Easy" },
    { id: 3, q: "What does useEffect hook do?", options: ["Manages state", "Handles side effects", "Creates context", "Memoizes values"], ans: 1, diff: "Easy" },
    { id: 4, q: "What is the virtual DOM?", options: ["A real browser DOM", "A lightweight copy of real DOM", "A CSS framework", "A server-side concept"], ans: 1, diff: "Easy" },
    { id: 5, q: "How do you pass data from parent to child in React?", options: ["State", "Props", "Context", "Redux"], ans: 1, diff: "Easy" },
    { id: 6, q: "Which method is called after component mounts in class components?", options: ["componentWillMount", "componentDidMount", "componentDidUpdate", "render"], ans: 1, diff: "Medium" },
    { id: 7, q: "What is React.memo used for?", options: ["Memoizing functions", "Preventing unnecessary re-renders", "Managing state", "Routing"], ans: 1, diff: "Medium" },
    { id: 8, q: "What does the key prop do in lists?", options: ["Styles the element", "Helps React identify changed items", "Adds event listeners", "Defines component type"], ans: 1, diff: "Medium" },
    { id: 9, q: "What is useCallback used for?", options: ["Memoize a function reference", "Memoize a computed value", "Fetch data", "Handle errors"], ans: 0, diff: "Medium" },
    { id: 10, q: "What is useMemo used for?", options: ["Memoize function", "Memoize computed value", "Handle side effects", "Update state"], ans: 1, diff: "Medium" },
    { id: 11, q: "What is Context API used for?", options: ["REST API calls", "Global state without prop drilling", "Animation", "Routing"], ans: 1, diff: "Medium" },
    { id: 12, q: "What does React.lazy() do?", options: ["Delays rendering", "Code splitting / lazy loading", "Caches components", "Optimizes images"], ans: 1, diff: "Hard" },
    { id: 13, q: "What is Suspense used for in React?", options: ["Error handling", "Showing fallback while lazy loading", "State management", "Event handling"], ans: 1, diff: "Hard" },
    { id: 14, q: "What is reconciliation in React?", options: ["Merging branches", "Diffing algorithm to update DOM", "Combining reducers", "Syncing state"], ans: 1, diff: "Hard" },
    { id: 15, q: "Which hook replaces componentDidMount and componentWillUnmount?", options: ["useState", "useReducer", "useEffect", "useRef"], ans: 2, diff: "Medium" },
    { id: 16, q: "What is useReducer?", options: ["Alternative to useState for complex logic", "Replaces Redux", "Fetches API data", "Creates refs"], ans: 0, diff: "Medium" },
    { id: 17, q: "What is prop drilling?", options: ["Passing props through many nested components", "Drilling CSS properties", "A React anti-pattern fix", "A performance issue"], ans: 0, diff: "Easy" },
    { id: 18, q: "What is the purpose of StrictMode?", options: ["Production optimization", "Highlights potential problems in development", "Enforces strict CSS", "Disables console logs"], ans: 1, diff: "Medium" },
    { id: 19, q: "What does ReactDOM.render() do?", options: ["Creates a component", "Renders React element into DOM", "Fetches data", "Routes pages"], ans: 1, diff: "Easy" },
    { id: 20, q: "What is a controlled component in React?", options: ["Component with no state", "Form element whose value is controlled by state", "Component using Redux", "Class component"], ans: 1, diff: "Medium" },
    { id: 21, q: "What hook gives access to DOM elements directly?", options: ["useState", "useEffect", "useRef", "useContext"], ans: 2, diff: "Medium" },
    { id: 22, q: "What is React Router used for?", options: ["State management", "Client-side navigation", "API calls", "Styling"], ans: 1, diff: "Easy" },
    { id: 23, q: "What is an uncontrolled component?", options: ["Component without props", "Form that stores its own state in DOM", "Stateless component", "Component with errors"], ans: 1, diff: "Medium" },
    { id: 24, q: "What does lifting state up mean?", options: ["Moving state to a higher component", "Adding more state", "Using Redux", "Creating global state"], ans: 0, diff: "Medium" },
    { id: 25, q: "What is a Higher Order Component (HOC)?", options: ["A component that returns JSX", "A function that takes and returns a component", "A class component", "A lifecycle method"], ans: 1, diff: "Hard" },
    { id: 26, q: "Which package is used for state management in large React apps?", options: ["Axios", "Redux", "Lodash", "Moment"], ans: 1, diff: "Easy" },
    { id: 27, q: "What is the difference between state and props?", options: ["No difference", "State is internal, props are external", "Props are mutable, state is not", "State is for class, props for functional"], ans: 1, diff: "Easy" },
    { id: 28, q: "What does batch updating mean in React 18?", options: ["Group multiple state updates into one render", "Update all components", "Async rendering", "Server rendering"], ans: 0, diff: "Hard" },
    { id: 29, q: "What is the React fiber architecture?", options: ["CSS framework", "New reconciliation engine in React 16", "A hook", "Error boundary"], ans: 1, diff: "Hard" },
    { id: 30, q: "What is an Error Boundary in React?", options: ["A try-catch for components", "A component that catches JS errors in child tree", "An error message component", "A debug tool"], ans: 1, diff: "Hard" },
  ],
  python: [
    { id: 101, q: "What is Python?", options: ["Compiled language", "Interpreted high-level language", "Assembly language", "Markup language"], ans: 1, diff: "Easy" },
    { id: 102, q: "Which keyword defines a function in Python?", options: ["function", "def", "fun", "define"], ans: 1, diff: "Easy" },
    { id: 103, q: "What is a list in Python?", options: ["Immutable sequence", "Mutable ordered collection", "Key-value pairs", "A set of unique items"], ans: 1, diff: "Easy" },
    { id: 104, q: "What is the difference between a list and a tuple?", options: ["No difference", "Tuples are immutable, lists are mutable", "Lists are faster", "Tuples allow duplicates"], ans: 1, diff: "Easy" },
    { id: 105, q: "What does len() function do?", options: ["Length of string only", "Returns number of items in object", "Counts digits", "Measures memory"], ans: 1, diff: "Easy" },
    { id: 106, q: "What is a dictionary in Python?", options: ["Ordered list", "Key-value pair collection", "Immutable sequence", "Sorted set"], ans: 1, diff: "Easy" },
    { id: 107, q: "What is a lambda function?", options: ["A named function", "An anonymous single-expression function", "A class method", "A decorator"], ans: 1, diff: "Medium" },
    { id: 108, q: "What is list comprehension?", options: ["Importing a list", "Compact way to create lists", "Sorting a list", "Filtering a list only"], ans: 1, diff: "Medium" },
    { id: 109, q: "What does the __init__ method do in a class?", options: ["Deletes object", "Initializes object attributes", "Returns object", "Prints object"], ans: 1, diff: "Medium" },
    { id: 110, q: "What is inheritance in Python OOP?", options: ["Copying a class", "Child class inheriting parent class properties", "Creating multiple objects", "Method overloading"], ans: 1, diff: "Medium" },
    { id: 111, q: "What is a decorator in Python?", options: ["A comment style", "A function that modifies another function", "A class attribute", "An import statement"], ans: 1, diff: "Hard" },
    { id: 112, q: "What is a generator in Python?", options: ["A function that returns a list", "A function that yields values lazily", "A random number generator", "A class factory"], ans: 1, diff: "Hard" },
    { id: 113, q: "What does yield do in Python?", options: ["Returns from function permanently", "Pauses function and returns value", "Raises exception", "Imports module"], ans: 1, diff: "Hard" },
    { id: 114, q: "What is the GIL in Python?", options: ["Global Import Lock", "Global Interpreter Lock", "General Input Lock", "Garbage Iterator Loop"], ans: 1, diff: "Hard" },
    { id: 115, q: "What is *args used for?", options: ["Keyword arguments", "Variable positional arguments", "Default arguments", "Required arguments"], ans: 1, diff: "Medium" },
    { id: 116, q: "What is **kwargs used for?", options: ["Variable positional args", "Variable keyword arguments", "Default values", "Unpacking lists"], ans: 1, diff: "Medium" },
    { id: 117, q: "What is slicing in Python?", options: ["Removing elements", "Extracting a portion of sequence", "Sorting list", "Copying deeply"], ans: 1, diff: "Easy" },
    { id: 118, q: "What is a set in Python?", options: ["Ordered collection", "Collection of unique elements", "Key-value store", "Mutable tuple"], ans: 1, diff: "Easy" },
    { id: 119, q: "What does map() function do?", options: ["Creates dictionary", "Applies function to each element", "Filters elements", "Reduces to single value"], ans: 1, diff: "Medium" },
    { id: 120, q: "What is the difference between deep copy and shallow copy?", options: ["No difference", "Deep copy copies nested objects too", "Shallow is slower", "Deep is for lists only"], ans: 1, diff: "Hard" },
    { id: 121, q: "What is exception handling in Python?", options: ["Avoiding errors", "Catching and handling runtime errors with try/except", "Logging errors", "Ignoring errors"], ans: 1, diff: "Medium" },
    { id: 122, q: "What does enumerate() do?", options: ["Counts elements", "Returns index-value pairs in iteration", "Sorts list", "Reverses list"], ans: 1, diff: "Medium" },
    { id: 123, q: "What is polymorphism in Python?", options: ["Same method name different behavior", "Multiple inheritance", "Function overloading", "Creating multiple objects"], ans: 0, diff: "Medium" },
    { id: 124, q: "What is the purpose of __str__ method?", options: ["Sorts object", "Returns string representation of object", "Initializes object", "Deletes object"], ans: 1, diff: "Medium" },
    { id: 125, q: "What does zip() function do?", options: ["Compresses files", "Combines multiple iterables element-wise", "Sorts two lists", "Merges dictionaries"], ans: 1, diff: "Medium" },
    { id: 126, q: "What is a module in Python?", options: ["A class", "A file containing Python code/functions", "A package", "A built-in function"], ans: 1, diff: "Easy" },
    { id: 127, q: "What is pip?", options: ["Python Integrated Package", "Package installer for Python", "Python Input Parser", "Performance improvement"], ans: 1, diff: "Easy" },
    { id: 128, q: "What is a virtual environment?", options: ["Cloud environment", "Isolated Python environment per project", "GUI framework", "Debug mode"], ans: 1, diff: "Medium" },
    { id: 129, q: "What is the difference between is and == in Python?", options: ["No difference", "== checks value, is checks identity", "is checks value", "== checks type"], ans: 1, diff: "Medium" },
    { id: 130, q: "What does the with statement do?", options: ["Conditional execution", "Context manager, auto-closes resources", "Loops through items", "Imports module"], ans: 1, diff: "Medium" },
    { id: 131, q: "What is __name__ == '__main__' used for?", options: ["Checking class name", "Running code only when file is executed directly", "Naming a function", "Exporting module"], ans: 1, diff: "Medium" },
    { id: 132, q: "What is recursion?", options: ["Looping with for", "A function calling itself", "Multiple inheritance", "Nested lists"], ans: 1, diff: "Medium" },
    { id: 133, q: "What is a frozen set?", options: ["A set with None values", "An immutable version of set", "A sorted set", "A set with integers only"], ans: 1, diff: "Hard" },
    { id: 134, q: "What is monkey patching?", options: ["Debugging technique", "Modifying classes/modules at runtime", "Unit testing", "Memory management"], ans: 1, diff: "Hard" },
    { id: 135, q: "What does collections.Counter do?", options: ["Counts file lines", "Counts occurrences of elements", "Counts class methods", "Measures execution time"], ans: 1, diff: "Medium" },
  ],
  java: [
    { id: 201, q: "What is Java?", options: ["Scripting language", "Platform-independent OOP language", "Compiled-only language", "A database"], ans: 1, diff: "Easy" },
    { id: 202, q: "What does JVM stand for?", options: ["Java Variable Machine", "Java Virtual Machine", "Java Verified Module", "Java Value Manager"], ans: 1, diff: "Easy" },
    { id: 203, q: "What is the difference between JDK, JRE, and JVM?", options: ["Same thing", "JDK > JRE > JVM (tools > runtime > interpreter)", "JVM > JRE > JDK", "No practical difference"], ans: 1, diff: "Medium" },
    { id: 204, q: "What is encapsulation?", options: ["Hiding implementation details", "Multiple inheritance", "Method overriding", "Abstract class"], ans: 0, diff: "Easy" },
    { id: 205, q: "What is the difference between == and .equals() in Java?", options: ["No difference", "== checks reference, .equals() checks value", "equals() checks reference", "== works only for strings"], ans: 1, diff: "Medium" },
    { id: 206, q: "What is an interface in Java?", options: ["A class with methods", "A contract with abstract methods only", "A final class", "A constructor type"], ans: 1, diff: "Medium" },
    { id: 207, q: "What is an abstract class?", options: ["Class with no methods", "Class that cannot be instantiated directly", "Final class", "Static class"], ans: 1, diff: "Medium" },
    { id: 208, q: "What is method overloading?", options: ["Same method name, different parameters", "Overriding parent method", "Hiding a method", "Abstract method"], ans: 0, diff: "Easy" },
    { id: 209, q: "What is method overriding?", options: ["Different return type", "Child class redefines parent class method", "Static method replacement", "Method with multiple params"], ans: 1, diff: "Easy" },
    { id: 210, q: "What is the final keyword used for?", options: ["Ending program", "Preventing modification of class/method/variable", "Finalizing garbage collection", "Importing last package"], ans: 1, diff: "Medium" },
    { id: 211, q: "What is a static method?", options: ["Method that belongs to instance", "Method that belongs to class, not instance", "Abstract method", "Final method"], ans: 1, diff: "Medium" },
    { id: 212, q: "What is garbage collection in Java?", options: ["Manual memory cleanup", "Automatic memory management", "Deleting variables", "Clearing screen"], ans: 1, diff: "Easy" },
    { id: 213, q: "What is a constructor?", options: ["A method with return type", "Special method to initialize objects", "A static method", "An interface method"], ans: 1, diff: "Easy" },
    { id: 214, q: "What is the difference between ArrayList and LinkedList?", options: ["No difference", "ArrayList uses array, LinkedList uses nodes", "LinkedList is faster always", "ArrayList uses more memory always"], ans: 1, diff: "Medium" },
    { id: 215, q: "What is a HashMap?", options: ["Ordered key-value store", "Unordered key-value store", "Synchronized map", "A tree structure"], ans: 1, diff: "Medium" },
    { id: 216, q: "What is exception handling in Java?", options: ["Avoiding errors", "Managing runtime errors using try-catch-finally", "Logging only", "Terminating program on error"], ans: 1, diff: "Medium" },
    { id: 217, q: "What is the difference between checked and unchecked exceptions?", options: ["No difference", "Checked are compile-time, unchecked are runtime", "Unchecked must be handled", "Checked are runtime errors"], ans: 1, diff: "Hard" },
    { id: 218, q: "What is multithreading in Java?", options: ["Running multiple programs", "Concurrent execution of multiple threads", "Multiprocessing", "Parallel compilation"], ans: 1, diff: "Hard" },
    { id: 219, q: "What does synchronized keyword do?", options: ["Speeds up code", "Ensures only one thread accesses block at a time", "Synchronizes databases", "Imports classes"], ans: 1, diff: "Hard" },
    { id: 220, q: "What is the Collections framework?", options: ["Framework for file I/O", "Set of classes for data structures", "GUI framework", "Network framework"], ans: 1, diff: "Medium" },
    { id: 221, q: "What is a lambda expression in Java 8?", options: ["A new class type", "Anonymous function shorthand", "A loop type", "An exception type"], ans: 1, diff: "Medium" },
    { id: 222, q: "What is Stream API in Java 8?", options: ["File streaming", "Functional-style operations on collections", "Network streaming", "I/O operations"], ans: 1, diff: "Hard" },
    { id: 223, q: "What is Optional in Java 8?", options: ["A nullable type", "Container to avoid NullPointerException", "A list type", "An interface"], ans: 1, diff: "Hard" },
    { id: 224, q: "What is the difference between String, StringBuilder, StringBuffer?", options: ["Same thing", "String immutable, Builder not thread-safe, Buffer thread-safe", "Builder is immutable", "Buffer is faster always"], ans: 1, diff: "Hard" },
    { id: 225, q: "What is polymorphism in Java?", options: ["Same method, different forms", "Multiple classes", "Inheritance only", "Interface only"], ans: 0, diff: "Medium" },
    { id: 226, q: "What does the this keyword refer to?", options: ["Parent class", "Current class instance", "Static context", "Next object"], ans: 1, diff: "Easy" },
    { id: 227, q: "What does super keyword do?", options: ["Refers to current class", "Refers to parent class", "Creates new object", "Overrides method"], ans: 1, diff: "Easy" },
    { id: 228, q: "What is an enum in Java?", options: ["A random number type", "A special class representing fixed constants", "An array type", "An interface"], ans: 1, diff: "Medium" },
    { id: 229, q: "What is autoboxing in Java?", options: ["Automatic type casting", "Auto conversion between primitive and wrapper", "Boxing algorithm", "Packing arrays"], ans: 1, diff: "Medium" },
    { id: 230, q: "What is the Comparable interface used for?", options: ["Comparing strings only", "Defining natural ordering for objects", "Sorting arrays", "Equals checking"], ans: 1, diff: "Medium" },
  ],
  dsa: [
    { id: 301, q: "What is the time complexity of binary search?", options: ["O(n)", "O(n²)", "O(log n)", "O(1)"], ans: 2, diff: "Easy" },
    { id: 302, q: "What data structure uses LIFO order?", options: ["Queue", "Stack", "Linked List", "Tree"], ans: 1, diff: "Easy" },
    { id: 303, q: "What data structure uses FIFO order?", options: ["Stack", "Tree", "Queue", "Heap"], ans: 2, diff: "Easy" },
    { id: 304, q: "What is the time complexity of accessing element in array?", options: ["O(n)", "O(log n)", "O(1)", "O(n²)"], ans: 2, diff: "Easy" },
    { id: 305, q: "What is a linked list?", options: ["Array with fixed size", "Linear data structure with nodes connected by pointers", "A hash table", "A tree"], ans: 1, diff: "Easy" },
    { id: 306, q: "What is a binary tree?", options: ["Tree with 2 levels", "Tree where each node has at most 2 children", "Tree with 2 roots", "Balanced tree"], ans: 1, diff: "Easy" },
    { id: 307, q: "What is a Binary Search Tree (BST)?", options: ["Tree with binary values", "BST where left < root < right", "A balanced tree", "A heap"], ans: 1, diff: "Medium" },
    { id: 308, q: "What is the worst case time complexity of quicksort?", options: ["O(n log n)", "O(n)", "O(n²)", "O(log n)"], ans: 2, diff: "Medium" },
    { id: 309, q: "What is the average time complexity of merge sort?", options: ["O(n²)", "O(n log n)", "O(n)", "O(log n)"], ans: 1, diff: "Medium" },
    { id: 310, q: "What is a hash table?", options: ["Sorted array", "Data structure with key-value pairs using hash function", "A linked list", "A binary tree"], ans: 1, diff: "Medium" },
    { id: 311, q: "What is a graph in data structures?", options: ["A chart", "Non-linear structure of vertices and edges", "A tree with cycles", "An adjacency matrix only"], ans: 1, diff: "Medium" },
    { id: 312, q: "What is BFS?", options: ["Backward First Search", "Breadth First Search", "Binary First Search", "Base First Search"], ans: 1, diff: "Easy" },
    { id: 313, q: "What is DFS?", options: ["Data First Search", "Depth First Search", "Directed First Search", "Dynamic First Search"], ans: 1, diff: "Easy" },
    { id: 314, q: "What is dynamic programming?", options: ["Dynamic typing", "Solving problems by breaking into subproblems and storing results", "Recursive only approach", "Greedy algorithm"], ans: 1, diff: "Hard" },
    { id: 315, q: "What is a min-heap?", options: ["Tree where parent > children", "Tree where parent <= children, root is minimum", "A sorted array", "A binary search tree"], ans: 1, diff: "Medium" },
    { id: 316, q: "What is the space complexity of merge sort?", options: ["O(1)", "O(log n)", "O(n)", "O(n²)"], ans: 2, diff: "Medium" },
    { id: 317, q: "What is a trie data structure?", options: ["A binary tree", "Tree for storing strings character by character", "A graph", "A hash map"], ans: 1, diff: "Hard" },
    { id: 318, q: "What is a circular linked list?", options: ["Linked list with no head", "Linked list where tail points back to head", "Doubly linked list", "Sorted linked list"], ans: 1, diff: "Medium" },
    { id: 319, q: "What is memoization?", options: ["Memorizing algorithms", "Caching results of expensive function calls", "Memory management", "Recursion optimization"], ans: 1, diff: "Hard" },
    { id: 320, q: "What is the time complexity of bubble sort?", options: ["O(n log n)", "O(log n)", "O(n²)", "O(n)"], ans: 2, diff: "Easy" },
    { id: 321, q: "What is a deque?", options: ["A stack only", "Double-ended queue, insert/delete from both ends", "A priority queue", "A circular array"], ans: 1, diff: "Medium" },
    { id: 322, q: "What is topological sort?", options: ["Sorting numbers", "Linear ordering of vertices in a DAG", "Sorting a tree", "Graph coloring"], ans: 1, diff: "Hard" },
    { id: 323, q: "What is Dijkstra's algorithm used for?", options: ["Minimum spanning tree", "Shortest path in weighted graph", "Topological sort", "Graph coloring"], ans: 1, diff: "Hard" },
    { id: 324, q: "What is a spanning tree?", options: ["Any tree in graph", "Subgraph connecting all vertices with no cycles", "Minimum weighted tree", "Complete binary tree"], ans: 1, diff: "Hard" },
    { id: 325, q: "What is the Floyd-Warshall algorithm?", options: ["Single source shortest path", "All pairs shortest path", "Minimum spanning tree", "Graph traversal"], ans: 1, diff: "Hard" },
    { id: 326, q: "What is an AVL tree?", options: ["Unbalanced BST", "Self-balancing BST", "A heap", "A red-black tree"], ans: 1, diff: "Hard" },
    { id: 327, q: "What is the time complexity of insertion in a balanced BST?", options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"], ans: 2, diff: "Medium" },
    { id: 328, q: "What is a priority queue?", options: ["FIFO queue", "Queue where element with highest priority is served first", "Stack with priority", "A sorted array"], ans: 1, diff: "Medium" },
    { id: 329, q: "What is the greedy algorithm approach?", options: ["Try all solutions", "Make locally optimal choice at each step", "Divide and conquer", "Backtracking"], ans: 1, diff: "Medium" },
    { id: 330, q: "What is backtracking?", options: ["Undoing code changes", "Algorithm that builds solutions incrementally and abandons invalid paths", "A sorting technique", "Graph traversal"], ans: 1, diff: "Hard" },
  ]
};

// Flatten all questions
const ALL_QUESTIONS = [
  ...QUESTIONS_DB.react,
  ...QUESTIONS_DB.python,
  ...QUESTIONS_DB.java,
  ...QUESTIONS_DB.dsa
];
